jenkinsci/junit-plugin

src/main/java/hudson/tasks/junit/TestResultAction.java

Would probably fix the test failure in https://github.com/jenkinsci/flaky-test-handler-plugin/pull/1 though that is better done by fixing the test to not call this constructor to begin with. @reviewbybees

Avoid NPE if someone calls a deprecated constructor

---

src/main/java/hudson/tasks/test/AbstractTestResultAction.java

A Jenkins instance running 1.554.3 was observed to crash in a thread running
```
Handling GET /job/…/test/trend : …
at java.lang.OutOfMemoryError.<init>()V (Unknown Source)
at java.util.Arrays.copyOf([Ljava/lang/Object;I)[Ljava/lang/Object; (Unknown Source)
at java.util.ArrayList.grow(I)V (Unknown Source)
at java.util.ArrayList.ensureCapacityInternal(I)V (Unknown Source)
at java.util.ArrayList.add(Ljava/lang/Object;)Z (Unknown Source)
at hudson.util.DataSetBuilder.add(Ljava/lang/Number;Ljava/lang/Comparable;Ljava/lang/Comparable;)V (DataSetBuilder.java:52)
at hudson.tasks.test.AbstractTestResultAction.buildDataSet(Lorg/kohsuke/stapler/StaplerRequest;)Lorg/jfree/data/category/CategoryDataset; (AbstractTestResultAction.java:260)
at …
```

Diagnosis/recovery for infinite loop in AbstractTestResultAction.buildDataSet

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/test/java/hudson/tasks/junit/SuiteResultTest.java

When `!keepLongStdio`, the stdout/stderr of passing tests is truncated to avoid memory pressure, under the assumption that you probably do not care about the details much. This is good, but it is useful to have some kind of limit even for failing tests. Otherwise a test that produces copious log output, then fails, can overwhelm the remoting channel and the Jenkins master heap. This patch sets the limit to be around 100K per incident (in JUnit, that means per test suite).
@reviewbybees (ref. ZD-24570)

Trim stdio even on failing tests, just to a 100× larger cutoff

---

src/main/resources/hudson/tasks/junit/JUnitResultArchiver/help-healthScaleFactor.html

This is a minor change one of our users noticed that the help for the health scale factor had some minor bugs.  I would believe this is correct due to the other values and multiplying them out but I have not tested with the plug-in itself to see if this is true.  If need be I can setup a testcase locally and take some screenshots.

Correct the help for the health scale factor

---

src/main/java/hudson/tasks/junit/ClassResult.java

ClassResult#freeze() method now calls ClassResult#tally() instead of having it's whole body repeated.
Since ClassResult class is already final, there's no chance for the tally method to be overridden, so no problem.

Refactored code duplication in ClassResult.

---

src/main/java/hudson/tasks/test/TestObject.java

Opening a test result with a empty className tag in junitReport.xml file results in a 404 page because the URL contains a empty path for the class.
This patch prevents this.

[JENKINS-27974]: Safe URL for empty className

---

src/main/java/hudson/tasks/junit/TestResultAction.java

[JENKINS-26077](https://issues.jenkins-ci.org/browse/JENKINS-26077)
@reviewbybees

[JENKINS-26077] Duplicated TestResultProjectAction

---

pom.xml
src/main/resources/lib/hudson/test/failed-test.jelly
src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java

The path can contain url-encoded special characters. Passing it to the javascript
function over `href="javascript:..."` decodes at least some of the characters so
`showFailureSummary` function search decoded version of element IDs and fails when
the decoded string differs. This change uses onclick event instead, where arguments
are not url-decoded.

[FIXED JENKINS-29383] Fix handling of special chars in aggregated matrix reports

---

src/main/resources/lib/hudson/test/failed-test.jelly

https://issues.jenkins-ci.org/browse/JENKINS-29613

[FIXED JENKINS-29613] Failure summary jumps to the top of the page when expanded/collapsed

---

src/main/resources/hudson/tasks/junit/CaseResult/list.jelly
src/main/resources/hudson/tasks/junit/ClassResult/body.jelly
src/main/resources/hudson/tasks/junit/ClassResult/list.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/list.jelly
src/main/resources/lib/hudson/test/aggregated-failed-tests.jelly
src/test/java/hudson/tasks/test/TestReportUiTest.java

Prevents wrapping duration text in JUnit test results.
https://issues.jenkins-ci.org/browse/JENKINS-24352
@reviewbybees 
Before:
After:

JENKINS-24352 - JUnit test result table wrapping duration text

---

src/main/java/hudson/tasks/junit/JUnitParser.java
src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
src/main/resources/hudson/tasks/junit/JUnitResultArchiver/config.jelly
src/main/resources/hudson/tasks/junit/JUnitResultArchiver/help-allowEmptyResults.html
src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java

This is an attempt at solving one aspect of JENKINS-12815 (https://issues.jenkins-ci.org/browse/JENKINS-12815). This implementation does not allow for setting the build status on missing files, but a simple check-box to allow empty results at all. I hope it is a reasonable compromise between the functionality needed by many (myself included) to allow for missing test files and not to clutter the GUI with too many options.

Added option allowing empty test results.

---

src/main/java/hudson/tasks/junit/TestResult.java

The phrase `<init>` as a test name is used in three places to
represent three independent types of error.  This is needlessly
ambiguous.  This patch removes that ambiguity so it is clear
which case is under consideration.

remove ambiguity in test errors

---

src/main/java/hudson/tasks/junit/PackageResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/hudson/tasks/junit/TestResultAction.java
src/main/java/hudson/tasks/test/AbstractTestResultAction.java

Currently, it is very simple to get a list of failed tests with a single line of code by calling `getFailedTests()` on the `TestResultAction`.  However, getting a list of passed or skipped tests is significantly more difficult.  To do that, you have to dig down to the `PackageResult` level, which not involves traversing further down into the data structures, but also means that you have to collect the results from each package individually.
The changes in this pull request aim to allow passed and skipped test results to be retrieved just as easily as failed ones by changing the way passed and skipped results are handled internally to be more similar to how failed results are handled.

Make it easier for scripts to retrieve passed and skipped test results

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/ClassResult.java
src/main/java/hudson/tasks/junit/PackageResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/hudson/tasks/test/TestObject.java
src/test/java/hudson/tasks/junit/JUnitParserTest.java

This pull request is focused on resolving occurrences of Sonar rule " UselessParenthesesCheck -     Useless parentheses around expressions should be removed to prevent any misunderstanding". You can find more information about the issues here:
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
Please let me know if you have any questions.
Sameer Misger

Fixing squid:UselessParenthesesCheck-Useless parentheses around expressions should be removed to prevent any misunderstanding

---

src/main/java/hudson/tasks/junit/ClassResult.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/test/java/hudson/tasks/junit/SuiteResultTest.java
src/test/resources/hudson/tasks/junit/junit-report-testsuite-time-attrs.xml

Testsuite duration can be retrieved from its time attribute if
it exists. Otherwise it will continue to be calculated from the sum
of it's testcases. ClassResult duration is now obtained from it's
cases' SuiteResult since it was just re-summing case durations.

Testsuite duration may be parsed from time attr

---

src/main/resources/lib/hudson/test/aggregated-failed-tests.jelly

The no-wrap class attribute was added some time ago to prevent the duration column from wrapping its text.
But for long test names the test name column still inserts a line break between the plus icon (to show/hide the failure details) and the test name.
This change should fix that.

Prevent wrapping for test name table cell

---

src/main/java/hudson/tasks/test/AbstractTestResultAction.java

Unconfirmed reports of this method being implicated in very slow responses to `…/test/trend`, possibly caused by a large number of loop iterations. Cf #13.
@reviewbybees

Option to cap, or at least log, number of iterations of AbstractTestResultAction.buildDataSet

---

pom.xml

Or more precisely, prior to 2.2.
@reviewbybees esp. @kohsuke

[JENKINS-29922] A dependency on symbol-annotation does not work in Jenkins 1.x

---

src/main/resources/hudson/tasks/junit/CaseResult/list.jelly
src/main/resources/hudson/tasks/junit/ClassResult/body.jelly
src/main/resources/hudson/tasks/junit/ClassResult/list.jelly
src/main/resources/hudson/tasks/test/AggregatedTestResultPublisher/TestResultAction/index.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/list.jelly
src/main/resources/lib/hudson/test/aggregated-failed-tests.jelly
src/test/resources/hudson/tasks/test/TrivialTestResult/body.jelly

This patch uses the `stripped` class for tables to give alternate rows a slightly different background color. Additionally it highlights the current row on hover.
Both effects are also used in other parts of the Jenkins UI, e.g. the build history panel on the left side.
This addresses https://issues.jenkins-ci.org/browse/JENKINS-32148

[JENKINS-32148] use alternate background for table rows, highlight row on hover

---

src/main/resources/hudson/tasks/junit/JUnitResultArchiver/config.jelly

I'm not sure if this actually works -- I was taking a 1-minute stab at fixing a usability annoyance. But the 1-item advanced section has caused usability... issues.

Don't bury AllowEmptyResults in Advanced

---

src/main/java/hudson/tasks/test/TestObject.java
src/test/java/hudson/tasks/test/TestObjectTest.java

I opened this pull request due to the `safe()` function not replacing the `<` and `>` characters. This was triggered due to the `cucumber-testresult-plugin` using the `getSafeName()` for Scenarios and Features as file names when publishing reports (https://github.com/jenkinsci/cucumber-testresult-plugin/blob/master/src/main/java/org/jenkinsci/plugins/cucumber/jsontestsupport/CucumberTestResultArchiver.java).
Cucumber Scenarios can have the `<` and `>` characters in the scenario names (https://github.com/cucumber/cucumber/wiki/Scenario-Outlines) and as such these unsafe characters were preventing the results from being published to Jenkins.

Added '<' and '>' as unsafe URI characters.

---

src/main/resources/hudson/tasks/junit/Messages_es.properties

Also GH warned: "We've detected the file encoding as ISO-8859-1. When you commit changes we will transcode it to UTF-8."

Fix typo: resultadod -> resultados

---

src/main/java/hudson/tasks/junit/TestResult.java
src/test/java/hudson/tasks/junit/TestResultTest.java
src/test/resources/hudson/tasks/junit/JENKINS-41134/TestSuite_first.xml
src/test/resources/hudson/tasks/junit/JENKINS-41134/TestSuite_second.xml
src/test/resources/hudson/tasks/junit/JENKINS-41134/TestSuite_second_dup_first.xml

This adds a test for JENKINS-41134, fix which will make the test pass will come after.

Fix JENKINS-41134

---

src/main/java/hudson/tasks/junit/History.java

This is meant to fix a bug at duration axis on history charts.

[FIXED JENKINS-29736] removed divide by 1000

---

src/main/java/hudson/tasks/junit/SuiteResult.java
src/main/java/hudson/tasks/junit/XMLEntityResolver.java

The resolver is useful only for parsing TestNG results. There
is no need to register the resolver as a global extension.
Please see a related discussion and reasoning at https://github.com/jenkinsci/jenkins/pull/2806

Do not register XMLEntityResolver as a global extension

---

src/main/resources/hudson/tasks/junit/ClassResult/list.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/list.jelly
src/main/resources/lib/hudson/test/aggregated-failed-tests.jelly

We are aligning values to the right but column headers are centered. It can get tricky to navigate in bigger tables.
Before:
After:

Align headers where fields are aligned

---

src/main/java/hudson/tasks/junit/SuiteResult.java

Dom4j leaks a fd when SaxReader.read(File) is used.
Let's rather use SaxReader.read(FileInputStream)
and close the stream ourself.
This file descriptor leak is specially annoying
on a Windows slave because it prevents from 
deleting the xml report at the end of the build
Signed-off-by: David Gageot <david@gageot.net>

Fix a file descriptor leak

---

src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
src/main/java/hudson/tasks/junit/TestResultAction.java

This will allow dependent plugins (like xunit one) to run TestDataPublishers

Expose test data publicly

---

src/main/java/hudson/tasks/junit/ClassResult.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/test/java/hudson/tasks/junit/TestResultTest.java
src/test/resources/hudson/tasks/junit/junit-report-time-aggregation-invalid.xml
src/test/resources/hudson/tasks/junit/junit-report-time-aggregation.xml
src/test/resources/hudson/tasks/junit/junit-report-time-aggregation2.xml

[JENKINS-37598](https://issues.jenkins-ci.org/browse/JENKINS-37598)

[JENKINS-37598] Inaccurate aggregation of multiple xmls containing case information about the same testsuite

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/JUnitParser.java
src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStepExecution.java
src/main/java/hudson/tasks/test/PipelineArgs.java
src/main/java/hudson/tasks/test/PipelineTestDetails.java
src/main/java/hudson/tasks/test/TabulatedResult.java
src/main/java/hudson/tasks/test/TestResultParser.java
src/test/java/hudson/tasks/junit/JUnitParserTest.java
src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java
src/test/java/hudson/tasks/junit/SuiteResult2Test.java
src/test/java/hudson/tasks/junit/SuiteResultTest.java
src/test/java/hudson/tasks/junit/TestResultTest.java
src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java

Yet more for [JENKINS-27395](https://issues.jenkins-ci.org/browse/JENKINS-27395)
On further inspection, I came to the conclusion that since
multiple-runs-per-TestResult was only possible for
`AggregatedTestResultAction`, which doesn't support Pipeline jobs in
the first place, it made more sense to simplify things and get rid of
the run-and-nodes tracking of suites in favor of just nodes.
This also necessitated gathreing the enclosing block names earlier,
but that's probably a good change anyway.

[JENKINS-27395] Removed per-run node tracking

---

src/main/java/hudson/tasks/test/AbstractTestResultAction.java

There are already null checks in TestResult.getPreviousResult() that calls AbstractRestResultAction.findCorrespondingResult() so presumably it's safe to return null here if the results aren't available.
The jenkins cucumber test result plugin (https://wiki.jenkins.io/display/JENKINS/Cucumber+Test+Result+Plugin) was getting a ClassCastException. This was being caused after having just installed the plugin and trying to call the json api as it was trying to get results from a previous build from before the plugin was installed:
Caused by: java.lang.ClassCastException: hudson.tasks.test.AggregatedTestResultAction$1 cannot be cast to hudson.tasks.test.TestResult
at hudson.tasks.test.AbstractTestResultAction.findCorrespondingResult(AbstractTestResultAction.java:252)
at …

Prevent unsafe cast to TestResult.

---

pom.xml

There's no scenario I can come up with where the `@Whitelisted` annotation on `TestResultSummary` would be relevant if you don't have `script-security` installed, so let's just make `script-security` optional like all the Pipeline plugins.

Make script-security dependency optional

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java

[JENKINS-48020](https://issues.jenkins-ci.org/browse/JENKINS-48020)
First, this changes `CaseResult#getFullDisplayName()` to include
stage/branch names like `CaseResult#getDisplayName()`, so that the
full information will show up in lists of failed tests, for example.
Second, stop using `CaseResult#getDisplayName()` for indexing
`CaseResult`s in `SuiteResult`. That method will spam warnings if
called too early in the run now due to `CaseResult#getRun()` being
called before the `SuiteResult`'s parent is set.
Third, fix `JUnitResultsStepTest#testTrends` to actually test what
it's supposed to, to fail if it doesn't find the expected display
names, to test full display names as well, and to use the same
filename for the test results each time due to one of the stages' test
file not containing …

[FIXED JENKINS-48020] Show stage in failed tests, fix warnings

---

src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStepExecution.java
src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java

[JENKINS-48196](https://issues.jenkins-ci.org/browse/JENKINS-48196)
If we've got a suite with a stage inside a parallel branch where the
stage and parallel branch have the same name, we should only include
that name once in the suite/case/etc display name - it's redundant to
display it twice.
There is a potential gotcha here if you've got multiple stages inside
a branch and one of those stages has the same name as the branch, but
I think that's an edge case we can live with for now.

[FIXED JENKINS-48196] Remove redundant branch names from case displays

---

src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStepExecution.java
src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java

[JENKINS-48178](https://issues.jenkins-ci.org/browse/JENKINS-48178)
This fixes currentBuild.result to be UNSTABLE after test failures are
encountered. We'll want to revisit this in the future once we have
more granular stage/step status, but going with
getContext().setResult(...) was, in retrospect, premature optimization.

[FIXED JENKINS-48178] Set run result rather than context result

---

src/main/java/hudson/tasks/test/AggregatedTestResultAction.java

We're experimenting with aggregating test results from pipelines.
If the child is not an AbstractBuild then child.owner is null while child.run is filled, this fixes that case.

Use Run instead of AbstractBuild in AggregatedTestResultAction

---

pom.xml
src/main/java/hudson/tasks/test/AggregatedTestResultPublisher.java
src/main/resources/hudson/tasks/test/Messages.properties

`Messages` is `@Restricted(NoExternalUse.class)`. We were just failing to enforce that before.

Updated to new parent

---

pom.xml

[JENKINS-53365](https://issues.jenkins-ci.org/browse/JENKINS-53365)
excluding a transitive plugin dependency is a recipe for disaster for
consumers of the plugin.
It will cause anyone who is depending on this plugin to have to declare
a dependency on the excluded plugin in order for the InjectedTest or
hpi:run to work.
Given that the optionality was removed earlier I am just removing the
exclusion, however I do not fully understand why the optionality on the
workflow-api could not have been retained.
@abayer @jglick @agentgonzo

[JENKINS-53365] do not exclude transitive plugin deps

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/test/java/hudson/tasks/junit/TestResultTest.java
src/test/resources/hudson/tasks/junit/SKIPPED_MESSAGE/skippedTestResult.xml

Example Data:
```
<?xml version="1.0" encoding="UTF-8"?><testsuite failures="0" name="cucumber.runtime.formatter.JUnitFormatter" skipped="1" tests="1" time="0.172697">
<testcase classname="Test Sample" name="Test Example" time="0.172697">
<skipped><![CDATA[Given skip This Test........................................................pending
]]></skipped>
</testcase>
</testsuite>
```

Ability to pull the skippedMessage from the skipped xml element text when there is no message attribute available.

---

src/main/java/hudson/tasks/junit/ClassResult.java
src/test/java/hudson/tasks/junit/TestResultTest.java
src/test/resources/hudson/tasks/junit/JENKINS-42438/junit-report-1.xml

When running Android tests the <testsuite> in the generated xml file
can contain multiple classes.
Thus setting the test class duration to the value of the test-suite is wrong.

JENKINS-42438 Correctly calculate test class duration.

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/test/java/hudson/tasks/junit/TestResultLinksTest.java
src/test/java/hudson/tasks/junit/TestResultTest.java

See [JENKINS-31660](https://issues.jenkins-ci.org/browse/JENKINS-31660)
In case the a test was skipped, we don't need to know if it had previous failures, which allows us to avoid loading a lot of data from the disk and avoid StackOverflowError (in case the test was always skipped, we avoid loading all the previous builds).
There are two methods that recompute the failedSince field, one of them handled skipped builds correctly, the other one did not. With this PR they will both use the same logic.

[JENKINS-31660] avoid reading unnecessary test results from disk

---

.mvn/extensions.xml
.mvn/maven.config
Jenkinsfile
pom.xml
src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStepExecution.java
src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java

See https://github.com/jenkinsci/workflow-api-plugin/pull/91 and [JENKINS-39203](https://issues.jenkins-ci.org/browse/JENKINS-39203). (I am intentionally not updating the status of that ticket or assigning it to myself until I am ready to merge/release all relevant changes to avoid giving users premature hope of a fix and so that I have clear answers for what will and won't work and when any fixes will be released.) Subsumes and is based on #96.
This PR adds a `WarningAction` to the `StepAtomNode` for `junit` steps with failing tests so that the actual stage containing the `junit` step can be visualized as unstable via https://github.com/jenkinsci/pipeline-graph-analysis-plugin/pull/25.
Desired reviewers: @abayer, @jglick, @car-roll

[JENKINS-39203] Mark JUnit steps with failing tests with WarningAction

---

src/main/java/hudson/tasks/test/TestObject.java

After running a hello-world Pipeline with some tests, I noticed junk in the system log:
```
2019-04-11 14:14:01.146+0000 [id=15]	INFO	hudson.tasks.test.TestObject#getRelativePathFrom: trying to get relative path, but it is not my ancestor, and we're not in a stapler request. Trying absolute hudson url...
2019-04-11 14:14:01.148+0000 [id=15]	INFO	hudson.tasks.test.TestObject#getRelativePathFrom: Here's our relative path: http://jenkins//job/sample-pipeline/2//testReport/junit/test/SomeTest/test6/
```
Seems to be very old code, not a recent addition. Note the incorrect double slashes in two spots in the URL path—harmless?

Avoid logging useless messages at INFO

---

Jenkinsfile
pom.xml
src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/hudson/tasks/test/AbstractTestResultAction.java
src/main/java/hudson/tasks/test/package.html

Making sure this plugin is constantly checked both building with JDK8 and JDK11.
This goes with the Jenkins Java 11 General Availability announcement made back in March, and we're making a pass to check plugins are looking good on a JDK11.
([to understand the Jenkinsfile content](https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines#Java11DeveloperGuidelines-MakesureyourpluginistestedinContinuousIntegrationonJava8andJava11atthesametime))
@jenkinsci/java11-support

Java 11 readiness: build both on JDK8 and JDK11

---

README.md
pom.xml

Move documentation from Wiki to GitHub

---

src/main/java/hudson/tasks/junit/TestNameTransformer.java
src/test/java/hudson/tasks/junit/TestNameTransformerTest.java

Attempt at a hotfix for [JENKINS-61787](https://issues.jenkins-ci.org/browse/JENKINS-61787). I am guessing Scala test name transformation was already broken when using an agent; let us not make the whole `junit` step crash when you are not even using that plugin!

[JENKINS-61787] Do not attempt to look up TestNameTransformer’s from an agent JVM

---

pom.xml
src/main/java/hudson/tasks/test/AbstractTestResultAction.java
src/main/java/hudson/tasks/test/TestResultActionIterable.java
src/main/java/hudson/tasks/test/TestResultProjectAction.java
src/main/java/hudson/tasks/test/TestResultTrendChart.java
src/main/java/hudson/tasks/test/TestResultTrendSeriesBuilder.java
src/main/resources/hudson/tasks/test/TestResultProjectAction/floatingBox.jelly
src/test/java/hudson/tasks/junit/TestResultPublishingTest.java

Hi 👋 
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
There's one behaviour change in that it shows passing tests instead of total tests,
thoughts?
This was based off of https://github.com/jenkinsci/warnings-ng-plugin/blob/8ff937365caf3559c19a1e592aa218359a278347/plugin/src/main/java/io/jenkins/plugins/analysis/core/model/JobAction.java#L181
cc @oleg-nenashev @jglick @uhafner @fqueiruga

Convert trend to ECharts

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/test/java/hudson/tasks/junit/CaseResultTest.java
src/test/java/hudson/tasks/junit/SuiteResultTest.java
src/test/java/hudson/tasks/junit/TestResultTest.java
src/test/resources/hudson/tasks/junit/JENKINS-30413.xml

[JENKINS-30413](https://issues.jenkins-ci.org/browse/JENKINS-30413)
So far TestCases were identified by their name only and this was causing troubles when different test suites contain identically named TestCases.
This PR solves this by storing TestCases names with unique pattern: <Test.Suite.Name>.TestCaseName>

[JENKINS-30413] Fix test age calculation when same test name exists in different package

---

src/main/resources/hudson/tasks/junit/History/index.jelly

The "Older" and "Newer" links are currently displayed in a concatenated manner, i.e. "OlderNewer". This PR adds a tiny amount of spacing to distinguish the two buttons more clearly.

JENKINS-62775: Increase spacing between "Older" and "Newer" buttons

---

src/main/java/hudson/tasks/test/TestResultTrendSeriesBuilder.java

Aggregated reports don't record the passed tests.
Picked up in JENKINS-63339 as the maven-plugin uses this base class.
Seems safer to just revert to the previous logic than to try patching in tracking of the passed tests.

JENKINS-63339 Fix aggregated report trend

---

src/main/java/hudson/tasks/junit/storage/TestResultImpl.java
src/main/java/hudson/tasks/junit/storage/TestResultStorage.java

Not all the hard problems in #142 have been worked on (I suppose), so we should not advertise these interfaces to rando plugin developers without a warning.

Mark types in hudson.tasks.junit.storage package as beta

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/test/java/hudson/tasks/junit/CaseResultTest.java

See https://github.com/jenkinsci/junit-plugin/pull/135#issuecomment-686469488. CC @mguillem

Avoid NPE from CaseResult.getName()

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/PackageResult.java
src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

Pluggable storage: Add stdout, stderr, stacktrace, fix caseresult loading

---

src/main/java/hudson/tasks/junit/ClassResult.java
src/main/java/io/jenkins/plugins/junit/storage/TestResultImpl.java
src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

Cases are populated when the class result is retrieved from the DB

Remove unneeded API in pluggable storage

---

README.md
src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
src/main/java/hudson/tasks/junit/JUnitTask.java
src/main/java/hudson/tasks/junit/TestResultAction.java
src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStep.java
src/main/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisher.java
src/main/resources/hudson/tasks/junit/JUnitResultArchiver/config.jelly
src/main/resources/hudson/tasks/junit/JUnitResultArchiver/help-checksName.html
src/main/resources/hudson/tasks/junit/pipeline/JUnitResultsStep/help-checksName.html
src/test/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisherTest.java
src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

Adds the ability to set a custom name for the Checks API for each junit invocation.
I could see a number of ways to skin this cat, so I've picked this one on a fairly arbitrary basis.
This is also my first contribution to a jenkins plugin so please forgive anything I've missed!

Allow setting custom checks name

---

src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
src/main/java/hudson/tasks/junit/TestResultAction.java
src/main/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisher.java
src/test/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisherTest.java
src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

This, I believe, should fix the problem described in #198. However, I'm at a bit of a loss as to how best to test it, short of mocking a checks publisher and inspecting calls to that.
fixes #198

Publish only results included in current invocation to checks api - fixes #198

---

src/main/resources/hudson/tasks/junit/CaseResult/list.jelly

Fixes #200 - fixing url creation when showing the single test case

Fixing build link in history table when viewing a Test method's history

---

src/main/resources/hudson/tasks/test/TestResultProjectAction/jobMain.jelly

Reverts jenkinsci/junit-plugin#255
No longer needed as of https://github.com/jenkinsci/jenkins/pull/5351/commits/a1b2e9702552aaf0cd8a47eba7eba97f105aeb36

Revert "Wrap project action in block element"

---

src/main/java/hudson/tasks/junit/XMLEntityResolver.java

TestNG outputs the following DTD line:
`<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">`
When using `XMLEntityResolver` on testng with https DTD, you end up with a NPE:
```
org.dom4j.DocumentException: null Nested exception: null
at org.dom4j.io.SAXReader.read(SAXReader.java:484)
at org.dom4j.io.SAXReader.read(SAXReader.java:343)
at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:178)
at hudson.tasks.junit.TestResult.parse(TestResult.java:348)
at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:281)
at hudson.tasks.junit.TestResult.parse(TestResult.java:206)
at hudson.tasks.junit.TestResult.parse(TestResult.java:178)
at hudson.tasks.junit.TestResult.<init>(TestResult.java:143)
at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:14 …
```

Add support for https testng DTD namespace

---

src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/hudson/tasks/test/DefaultTestResultParserImpl.java
src/main/java/hudson/tasks/test/TestResultParser.java

Changing slave to agent, and master to controller as part of [JENKINS-65398](https://issues.jenkins.io/browse/JENKINS-65398 )

[JENKINS-65398] terminology update

---

src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStep.java
src/main/java/hudson/tasks/test/TestObject.java
src/test/java/hudson/tasks/test/AggregatedTestResultPublisherTest.java
src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

Remove guava usage from everywhere except for a single test class due to the usage of `workflow-api` graph analysis

Remove guava usage

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/test/java/hudson/tasks/junit/TestResultLinksTest.java
src/test/resources/hudson/tasks/junit/SKIPPED_MESSAGE/afterSkippedResult.xml

- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
See https://issues.jenkins.io/browse/JENKINS-57882
When fixing https://issues.jenkins.io/browse/JENKINS-31660 I made sure `failedSince` is computed by only checking one build instead of loading the whole history. If the previous build is skipped, it doesn't have `failedSince` set and current build is considered to be failing since build 0.
With this change `failedSince` should be reset to current build number after a skipped run.

[JENKINS-57882] Fix age of failed tests if previous build was skipped

---

src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStep.java
src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStepExecution.java
src/main/resources/hudson/tasks/junit/JUnitResultArchiver/config.jelly
src/main/resources/hudson/tasks/junit/JUnitResultArchiver/help-skipMarkingBuildUnstable.html
src/main/resources/hudson/tasks/junit/pipeline/JUnitResultsStep/help-skipMarkingBuildUnstable.html
src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java

When using the pipeline step with `skipMarkingBuildUnstable: true`, the corresponding node will still be
marked as unstable.
Fixes https://github.com/jenkinsci/junit-plugin/issues/278

[JENKINS-43692] Allow to not mark build as unstable on test failure

---

src/main/java/hudson/tasks/junit/JUnitParser.java
src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java

Assertions are by default disabled on the JVM. The previous use of `assert` therefore might have missed cases of empty test results in many Jenkins setups.
Using `AbortException` additionally provides more meaningful output in the build console.

Improve handling of missing & empty test result files

---

src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

I observed this stack trace in a recent BOM run:
```
com.thoughtworks.xstream.security.ForbiddenClassException: org.jenkinsci.plugins.database.h2.LocalH2Database
at com.thoughtworks.xstream.security.NoTypePermission.allows(NoTypePermission.java:26)
at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:74)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:125)
at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32) …
```

Compatibility with XStream 1.4.18

---

src/main/java/hudson/tasks/junit/TestResult.java

This is an outdated feature that doesn't reflect modern build tools that won't rebuild if all the inputs are the same (and they aren't forced to rebuild)
A multitude of hacks for gradle that are no longer needed after this:
https://stackoverflow.com/questions/13879667/how-to-fix-test-reports-were-found-but-none-of-them-are-new-did-tests-run-in
Seems like there was no test coverage for this and I don't think it makes sense to add any for a non feature
Fixes https://github.com/jenkinsci/junit-plugin/issues/201

Don't error on old test reports

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java
src/test/resources/hudson/tasks/junit/pipeline/ageReset-1.xml
src/test/resources/hudson/tasks/junit/pipeline/ageReset-2.xml

This causes test case resolution to be ambiguous if resolved from the
wrong test suite.
The consequence is for a failing test case that its age could reset
unexpectedly.

Disambiguate a case where multiple test suites have the same name

---

pom.xml

Undoes #375. Now that the plugin BOM has been updated to cross the Jackson/Jersey flag day in https://github.com/jenkinsci/bom/pull/1011, we no longer need to declare an explicit version.

Bump plugin BOM from 1210.vcd41f6657f03 to 1280.vd669827e38cd

---

pom.xml
src/main/java/hudson/tasks/junit/History.java
src/main/java/hudson/tasks/test/TestResultDurationChart.java
src/main/java/hudson/tasks/test/TestResultProjectAction.java
src/main/java/hudson/tasks/test/TestResultTrendChart.java
src/main/resources/hudson/tasks/junit/History/index.jelly
src/main/resources/hudson/tasks/test/TestResultProjectAction/floatingBox.jelly
src/main/webapp/history/history.css
src/main/webapp/history/history.js
src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java
src/test/java/hudson/tasks/junit/TestResultPublishingTest.java
src/test/java/hudson/tasks/test/AggregatedTestResultPublisherTest.java
src/test/java/hudson/tasks/test/helper/WebClientFactory.java

Bootstrap 5 has been released and requires some changes in markup and JS. Additionally, (due to the migration of ECharts to Bootstrap 5) trend charts are now configurable using a dialog.
Upstream PR: jenkinsci/echarts-api-plugin#124

Upgrade trends and detail views to Bootstrap 5

---

src/main/resources/hudson/tasks/junit/CaseResult/list.jelly
src/main/resources/hudson/tasks/junit/ClassResult/body.jelly
src/main/resources/hudson/tasks/junit/ClassResult/list.jelly
src/main/resources/hudson/tasks/junit/History/index.jelly
src/main/resources/hudson/tasks/test/AggregatedTestResultPublisher/TestResultAction/index.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/list.jelly
src/main/resources/lib/hudson/test/aggregated-failed-tests.jelly
src/test/resources/hudson/tasks/test/TrivialTestResult/body.jelly

Addressing the comment from https://github.com/jenkinsci/junit-plugin/pull/347#issuecomment-1115122097
The test table does currently render like
The change proposed gets a rid of the wrong pane argument and renders tables fine again:

Improve jenkins-table layout

---

pom.xml

Need to bump 1.54 to a newer version of bom to avoid cycle dependency between jackson api and jersey api.

bump bom to 1500.ve4d05cd32975

---

pom.xml
src/main/java/hudson/tasks/junit/History.java
src/main/java/hudson/tasks/test/TestResultDurationChart.java
src/main/java/hudson/tasks/test/TestResultProjectAction.java
src/main/java/hudson/tasks/test/TestResultTrendChart.java
src/main/resources/hudson/tasks/junit/History/index.jelly
src/main/resources/hudson/tasks/test/TestResultProjectAction/floatingBox.jelly
src/main/webapp/history/history.css
src/main/webapp/history/history.js
src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java
src/test/java/hudson/tasks/junit/TestResultPublishingTest.java
src/test/java/hudson/tasks/test/AggregatedTestResultPublisherTest.java
src/test/java/hudson/tasks/test/helper/AbstractTestResultLink.java
src/test/java/hudson/tasks/test/helper/WebClientFactory.java

Clean cherry-pick of #272 and #359 onto the 1.54.x line. See the test failures in https://ci.jenkins.io/job/Tools/job/bom/job/PR-1059/50/ - I have no idea why current PCT doesn't fail in this way, but my improved framework from JENKINS-45047 catches this (legitimate, I think) compatibility problem on the 1.54.x line. Cherry-picking the mentioned PRs resolves the issue for me locally when running PCT with JENKINS-45047.
CC @jetersen @timja

Backports to 1.54.x

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
src/main/java/hudson/tasks/junit/XMLEntityResolver.java
src/main/java/hudson/tasks/test/TestObject.java
src/main/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisher.java
src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

Got these baffling errors when running PCT with `copyartifact` in the managed set in https://github.com/jenkinsci/bom/pull/1385:
- https://ci.jenkins.io/job/Tools/job/bom/job/PR-1385/3/testReport/junit/(root)/ArchitectureTest/pct_checks_api_2_319_x___NO_JENKINS_INSTANCE_CALL/
- https://ci.jenkins.io/job/Tools/job/bom/job/PR-1385/3/testReport/junit/(root)/ArchitectureTest/pct_checks_api_2_319_x___NO_FORBIDDEN_PACKAGE_ACCESSED/
```
Architecture Violation [Priority: MEDIUM] - Rule 'no classes that do not have simple name 'JenkinsFacade' should call method Jenkins.getInstance() or should call method Jenkins.getInstanceOrNull() or should call method Jenkins.getActiveInstance() or should call method Jenkins.get()' was violated (2 times):
Method …
```

EOL usages of `StringUtils`

---

src/test/java/hudson/tasks/junit/TestResultPublishingTest.java

With `bootstrap5-api#5.2.0-3` the `history` text is inside a div with a `card-header` class instead inside the div with `card-body` this change will make the test work for both versions and IMO makes the test a bit less fragile, for example when running the PCT.
Updating the dependency would need a core bump and I am not sure how difficult that would be, and TBH I do not have time to do that. Anyway this change should be fine even after the core and boostrap5 update.

Check the card and not the card-body in TestResultPublishingTest

---

pom.xml
src/main/resources/hudson/tasks/junit/CaseResult/summary.jelly
src/main/resources/lib/hudson/test/failed-test.jelly

The change proposed replaces the tango icons with ionicons in the test overview.
Before:
After:

Use ionicons in test result overview

---

src/main/resources/hudson/tasks/test/TestResultProjectAction/floatingBox.jelly
src/main/resources/hudson/tasks/test/TestResultProjectAction/junit-trend-color-switcher.js

Hello :wave: 
Here's another Hacktoberfest Pull Request to solve [JENKINS-69657](https://issues.jenkins.io/browse/JENKINS-69657), by un-inlining floatingBox.jelly, and then making a step forward towards CSP adoption in Jenkins.
Before submitting the PR, I tested the existing code, removed the script to show that my test was not working anymore, un-inlined the test and checked that I worked again. Here it is working with the script un-inlined (which is similar to the behavior before the PR):
Thanks a lot for your review, let me know if there's anything missing I can take care of :smile: 
Have a great day!

[JENKINS-69657] Un-inlining floatingBox.jelly for CSP compliance

---

src/main/resources/hudson/tasks/test/AbstractTestResultAction/show-failures.js
src/main/resources/hudson/tasks/test/AbstractTestResultAction/summary.jelly

Hello there :wave:
Hacktoberfest PR here to solve [JENKINS-69656](https://issues.jenkins.io/browse/JENKINS-69656), by un-inlining AbstractTestResultAction/summary.jelly, and then making a step forward towards CSP adoption in Jenkins.
I tested that PR by following the details shared in the Jira ticket, and ensured my contribution didn't break the
current behavior.
While extracting the inline script to a js file, I also did a little bit of refactoring to the JavaScript source code, I
hope that's OK. Let me know if you don't like that part and I'll revert to the previous content of the JavaScript part.
Thanks a lot for your review, let me know if there's anything missing I can take care of :smile:
Have a great day!

[JENKINS-69656] Un-inlining AbstractTestResultAction/summary.jelly for CSP compliance

---

src/main/java/hudson/tasks/test/TestResult.java
src/test/java/hudson/tasks/junit/CaseResultTest.java

For a plugin using maven-release-plugin, I would recommend that this PR should be merged using merge-commit, not using squash-commit or rebase-commit, to ensure the commits related to the release are on the history of the default branch. Unsure about JEP-229.

Merge back SECURITY-2888 fix into master

---

src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/io/jenkins/plugins/junit/storage/TestResultImpl.java
src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

There's an issue that testReport/api/json doesn't display the suites list. Add the missing getSuites method in the TestResultImpl interface, and integrate it with Junit TestResult.
junit-sql-storage plugin will adopt this interface once it is released.

Add getSuites() method in TestResultImpl

---

pom.xml

As a workaround until jenkinsci/plugin-pom#705 is fixed and propagated, the kotlin version is explicitly set to match what okhttp-api-plugin provides.
This prevents a RequireUpperBoundDeps failure to be triggered for different kotlin versions in the okhttp-api-plugin dependency subtree.
More information in the related issue:
#504

Manage kotlin version to work around RequireUpperBoundDeps failure (#504)

---

src/main/java/hudson/tasks/junit/ClassResult.java
src/main/java/hudson/tasks/junit/PackageResult.java
src/main/java/hudson/tasks/junit/TestAction.java
src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/hudson/tasks/test/TabulatedResult.java
src/main/resources/hudson/tasks/junit/ClassResult/body.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
src/test/java/hudson/tasks/junit/CustomColumnsTest.java
src/test/java/hudson/tasks/junit/rot13/Rot13CaseAction.java
src/test/java/hudson/tasks/junit/rot13/Rot13CipherAction.java
src/test/java/hudson/tasks/junit/rot13/Rot13ClassAction.java
src/test/java/hudson/tasks/junit/rot13/Rot13PackageAction.java
src/test/java/hudson/tasks/junit/rot13/Rot13Publisher.java
src/test/java/hudson/tasks/junit/rot13/Rot13TestAction.java
src/test/resources/hudson/tasks/junit/junit-report-494.xml
src/test/resources/hudson/tasks/junit/rot13/Rot13CaseAction/tablerow.jelly
src/test/resources/hudson/tasks/junit/rot13/Rot13ClassAction/casetableheader.jelly
src/test/resources/hudson/tasks/junit/rot13/Rot13ClassAction/tablerow.jelly
src/test/resources/hudson/tasks/junit/rot13/Rot13PackageAction/casetableheader.jelly
src/test/resources/hudson/tasks/junit/rot13/Rot13PackageAction/classtableheader.jelly
src/test/resources/hudson/tasks/junit/rot13/Rot13PackageAction/tablerow.jelly
src/test/resources/hudson/tasks/junit/rot13/Rot13TestAction/casetableheader.jelly
src/test/resources/hudson/tasks/junit/rot13/Rot13TestAction/packagetableheader.jelly

Add optional jelly hooks that allow TestActions to contribute custom columns to tables that list CaseResults, ClassResults and PackageResults.
More details in the corresponding enhancement issue:
Fixes https://github.com/jenkinsci/junit-plugin/issues/494

Make it possible to include custom columns from TestActions in case, class and package tables

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/test/java/hudson/tasks/junit/SuiteResultTest.java

Continues #520 by just avoiding the core regression (if it is even considered valid).
There may be other Unicode characters which cause problems in XML serialization; for purposes of this PR I am focusing just on NUL.

[JENKINS-71139] Do not even try to save NULs

---

src/test/java/hudson/tasks/junit/TestResultTest.java

Minor simplification after #520.

`TestResultTest` can just reuse `TestResultAction.XSTREAM`

---

src/main/resources/hudson/tasks/test/AbstractTestResultAction/summary.jelly

The [`showLink` HTML anchor element](https://github.com/jenkinsci/junit-plugin/blob/19a5192cc1fc758a680695463392c2388318f59a/src/main/resources/hudson/tasks/test/AbstractTestResultAction/summary.jelly#L67) is only rendered server-side when fewer tests are displayed on the page than exist in the job result.
So if the job passes (zero failures displayed, zero failures exist), or if there are up to ten failures (up-to-ten failures displayed, up-to-ten failures exist), then the `showLink` HTML element won't be present on the page.
The associated `show-failures.js` adjunct code attempts to add an `onclick` event handler to a `showLink`-ID'd element on the page after the HTML DOM loads: https://github.com/jenkinsci/junit-plugin/blob/19a5192cc1fc758a680695463392c2388318f59a/src/main/resources/hud …

Test results summary: fix JavaScript console error when 'showLink' HTML element is missing

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/hudson/tasks/test/TestResult.java
src/main/resources/hudson/tasks/junit/CaseResult/index.jelly
src/main/resources/hudson/tasks/junit/CaseResult/summary.jelly
src/test/java/hudson/tasks/junit/CaseResultTest.java
src/test/java/hudson/tasks/junit/SuiteResultTest.java
src/test/resources/hudson/tasks/junit/junit-report-with-properties.xml

This PR adds support for the 'properties'  in a junit file.
More specifically it parses the properties node in the JUnit file and the properties of the the testcases are displayed along the other elements of the test execution (stdout, stderr, ...) 
Properties are often used to give describe the context of a test execution and having this information under the eye when looking at a test result seems valuable.
Properties are also used to attach files to a test result. This has not been handled in this PR.
This work is based on the ideas of Thomas Dee (https://github.com/jenkinsci/junit-plugin/pull/129)

Add support for 'properties'

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/JUnitParser.java
src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
src/main/java/hudson/tasks/junit/JUnitTask.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStep.java
src/main/resources/hudson/tasks/junit/JUnitResultArchiver/config.jelly
src/test/java/hudson/tasks/junit/CaseResultTest.java
src/test/java/hudson/tasks/junit/SuiteResultTest.java
src/test/java/hudson/tasks/junit/TestResultTest.java

If 'false' the properties attached to a test suite or a test case are ignored.
By default the properties are ignored.

Add a "keepProperties" option

---

src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

While working on a different core PR, I noticed this plugin was using vanilla XStream rather than the Jenkins-specific `XStream2` in one test. Since we generally prefer XStream2, and since the other test in this repository already uses XStream2, and since using XStream2 doesn't make the test start failing, I thought it would be best to make this usage consistent with the other test in this repository and with our general preference for XStream2.

Use `XStream2` where possible

---

src/main/java/hudson/tasks/test/TestResultProjectAction.java

This fixes chart trend after moving from default storage to external storage
Fixes https://github.com/jenkinsci/junit-plugin/issues/570
Instead of loading forever just return an empty trends chart.
Create build with local storage
Switch to external storage
Check that there is no exception
**Before**
**After**
Triggering more build continue to rebuild the trend chart
```[tasklist]
```
The situation is not ideal but I think is better than before.
Regards,

Fix chart trend after moving from default storage to external storage

---

src/test/java/hudson/tasks/test/helper/TestResultsPage.java

Fixes https://github.com/jenkinsci/junit-plugin/issues/588
There's now an SVG in the link with the text Unstable. The previous API does a value comparison which isn't possible to make work without including the whole svg inline exactly the same.
Checking the link destination does the same thing here.

Fix AggregatedTestResultPublisherTest on 2.434+

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/ClassResult.java
src/main/java/hudson/tasks/junit/PackageResult.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/test/java/hudson/tasks/junit/SuiteResultTest.java
src/test/java/hudson/tasks/junit/TestResultTest.java
src/test/resources/hudson/tasks/junit/junit-report-testsuite-various-timestamps.xml

…s, test packages, and test suites
This pull request is to add information about start times to the different test result classes. Start times are recorded using epoch milliseconds. Many tests in JUnit (and even more converted to JUnit via other plugins i.e. xUnit) include start times for test suites as well as test cases which could be useful information for third-party plugins to have. The default value is -1 for an unset start time and the package start time is the earliest start time of its test cases. Additionally, the overall test result start time is the earliest set start time of a SuiteResult. The largest adds are the parseTime method for parsing the epoch millisecond time from a timestamp and the logic for setting start times. It is intended to be as non-invasive as possible, so …

Add start time fields and logic for setting start time of results in epoch milliseconds

---

src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

Discovered in https://github.com/jenkinsci/bom/pull/3057 when trying to add `database-sqlite` to BOM. Both SQLite and H2 database plugins attempt to set themselves as the default, and when SQLite wins then this test fails. Fixed by changing the test to not make any assumptions about the default and instead explicitly set the database to the one the test expects.
Tested in context in PCT. Passes after this PR.

Allow PCT testing with `database-sqlite`

---

src/main/java/hudson/tasks/junit/History.java
src/main/java/hudson/tasks/junit/HistoryTestResultSummary.java
src/main/java/hudson/tasks/junit/TestResult.java
src/main/resources/hudson/tasks/junit/History/history.js
src/main/resources/hudson/tasks/junit/History/index.jelly
src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

and some minor cleanup at the same time, bunch of unused variables mostly.
Also fixed clicking on builds in the charts, variable wasn't defined properly before
cc @mdealer
noticed in https://github.com/jenkinsci/junit-sql-storage-plugin/pull/430
caused by https://github.com/jenkinsci/junit-plugin/pull/625
manually tested both junit and junit-sql-storage

Restore compatiblity with junit-sql-storage

---

pom.xml

Stop bundling the `jfreechart` and `jcommons` JAR files, as they are already shipped in the WAR file by Jenkins core.
`mvn clean verify -Dtest=InjectedTest`

Slim down JPI

---

pom.xml
src/main/java/hudson/tasks/junit/History.java

#625 added a dependency on `ssj`, which in turn picked up a few additional dependencies. I think we can avoid some of these dependencies to reduce the size of the HPI, avoid unusual licenses, and reduce supply chain risk by excluding all dependencies of `ssj` except for `commons-math3`.
```
[INFO] +- ca.umontreal.iro.simul:ssj:jar:3.3.2:compile
[INFO] |  +- colt:colt:jar:1.2.0:runtime
[INFO] |  |  \- concurrent:concurrent:jar:1.3.4:runtime
[INFO] |  +- com.github.rwl:optimization:jar:1.3:runtime
[INFO] |  \- org.apache.commons:commons-math3:jar:3.6.1:runtime
```
While reviewing the update, some of these dependencies stood out to me as being a bit unusual. 
* `colt:colt`
* The main homepage seems to be https://dst.lbl.gov/ACSSoftware/colt/, which offers `jar` downloads but does not mention …

Exclude all transitive dependencies of `ssj` besides `commons-math3` and replace linear regression implementation

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/hudson/tasks/junit/TestResultAction.java

Amends #625. @olamy recently saw a bunch of these log messages, which were added in that PR I guess to help detect slow loading, but they are not really useful without indicating which build is relevant:
```
2024-08-22 08:03:49.329+0000 [id=465]	WARNING	h.tasks.junit.TestResultAction#getResult: TestResultAction.load took 1060 ms.
```
This PR does 3 main things:
* For the new log messages added in #625, it adds either `Run.toString()` or `File.toString()` to the message to provide context
* It removes the hard-coded `Class.method` parts of the messages, which are added automatically by the default Jenkins logger
* It changes the visibility of the new static `parse` methods in #625 that as far as I understand were only intended for internal use from `public` to package-private. This plugin …

Improve recently added log messages by adding context to indicate which build is relevant

---

src/main/java/hudson/tasks/junit/CaseResult.java

We have generative tests that generate 10,000 test cases. These have recently started to sometimes hang for one hour before completing. We are not yet sure why (we have some hypotheses), but by taking thread dumps we can see that the coordinating node is stuck on populating a TreeMap which causes expensive string concatenations. This PR optimizes this to avoid concatenations while keeping the same behavior.
Thread dump where the coordinating node apparently gets stuck:
```
at java.base@21.0.3/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:326)
at java.base@21.0.3/java.lang.StringConcatHelper.prepend(StringConcatHelper.java:343)
at java.base@21.0.3/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
at …
```

Avoid String concatenation in compareTo

---

src/main/java/hudson/tasks/test/TestResult.java

cc @jglick @lemeurherve 
I've seen builds failing in the wild during `junit` step execution with an exception like
```
java.lang.NullPointerException: Cannot invoke "hudson.model.Run.getRootDir()" because "this.run" is null
at PluginClassLoader for junit//hudson.tasks.junit.TestResultAction.getDataFilePath(TestResultAction.java:154)
at PluginClassLoader for junit//hudson.tasks.junit.TestResultAction.loadCached(TestResultAction.java:317)
at PluginClassLoader for junit//hudson.tasks.junit.TestResultAction.load(TestResultAction.java:279)
at PluginClassLoader for junit//hudson.tasks.junit.TestResultAction.getResult(TestResultAction.java:166)
at PluginClassLoader for junit//hudson.tasks.junit.TestResultAction.getResult(TestResultAction.java:70)
at PluginClassLoader for …
```

Defending against past corrupt builds

---

src/main/java/hudson/tasks/test/AggregatedTestResultPublisher.java
src/main/resources/hudson/tasks/test/AggregatedTestResultPublisher/config.jelly

https://issues.jenkins.io/browse/JENKINS-73943
I've renamed the check method and dropped `checkUrl` attribute completely to let https://github.com/jenkinsci/jenkins/blob/dc4ad7e1a872e6dd9504f6c1ff1f95d84ca6046b/core/src/main/java/hudson/util/FormValidation.java#L625-L727 do its magic and wire things up for us. 
While `doCheck` sounded generic to me I found no places in code referencing it, so I assume it's safe to rename.
https://www.loom.com/share/27c91cc2a4d9480c867ed7cca651bd77?sid=ad8da66b-e52e-4e6e-bfc1-3b9525fb384d
https://www.loom.com/share/aaca1ff0b6274d44a102257baacc9fd9?sid=c8d997ed-11d7-4165-825c-ce5d2defcee7

[JENKINS-73943] Remove legacy `checkUrl` usage in AggregatedTestResutPublisher/config.jelly

---

src/main/resources/hudson/tasks/junit/History/history.js
src/main/resources/hudson/tasks/junit/History/index.jelly

https://issues.jenkins.io/browse/JENKINS-73946
Going to the history page and changing the values in the dropdowns is enough to trigger the affected code.
https://www.loom.com/share/37c4c276c3a14d2bab38168eb40f7af1?sid=310bc533-b971-4969-9a53-2098f7b3cffc
https://www.loom.com/share/170fb279203a4b38add532a1584cc87e?sid=45a8a87a-e919-4357-a836-0d87bf5dc1d9

[JENKINS-73946] Remove inline event handlers in `History/index.jelly`

---

src/main/resources/hudson/tasks/junit/ClassResult/body.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
src/test/resources/hudson/tasks/test/TrivialTestResult/body.jelly

Fixes #659
- `mvn clean verify`
- Reproduced the problem described in the ticket in Firefox and 2.479.1 before this PR, could no longer reproduce after this PR
- Attempted but failed to write an automated test with HtmlUnit, as I could not reproduce the problem in HtmlUnit but could in Firefox

URL-encode links to tests

---

src/main/resources/hudson/tasks/test/TestObject/sidepanel.jelly

Replace tango icon with modern symbol for history link
**Before**
After
Visual. See screenhost.

Replace tango icon with modern symbol for history link

---

pom.xml
src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/ClassResult.java
src/main/java/hudson/tasks/junit/PackageResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/hudson/tasks/test/AggregatedTestResultPublisher.java
src/main/java/hudson/tasks/test/TestObject.java
src/main/java/hudson/tasks/test/TestResultProjectAction.java
src/main/java/io/jenkins/plugins/junit/storage/JunitTestResultStorageConfiguration.java
src/main/resources/hudson/tasks/junit/History/index.jelly
src/main/resources/hudson/tasks/test/TestObject/sidepanel.jelly
src/main/resources/hudson/tasks/test/TestResultProjectAction/index.jelly
src/test/java/io/jenkins/plugins/junit/storage/benchmarks/TrendGraphBenchmark.java

Migrate from EE 8 to EE 9, at least in non-deprecated methods. This was tested with BOM/PCT.

Migrate from EE 8 to EE 9

---

src/main/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisher.java
src/test/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisherTest.java

These changes remove the hard-coded summary that links to the repository issue page.
I had a peak on how the `xunit` plugin provides such [status check details](https://github.com/jenkinsci/xunit-plugin/blob/4bf589c23c09a1988cf3e641e48d3251563814ac/src/main/java/org/jenkinsci/plugins/xunit/XUnitChecksPublisher.java#L85-L86).
They split test result details from overall summary.
Unfortunately, `github-checks-plugin` and `gitea-checks-plugin` seem to use different parts of the provided status check information. That's why every test report on any Jenkins plugin already has the `passed: xyz` as status check details.
Gitea seems to receive the static repo issue "fallback" instead.
So, splitting the currently provided information like `xunit` does it would probably be a somewhat breaking …

Reuse title information as summary

---

src/main/resources/hudson/tasks/junit/CaseResult/list.jelly
src/main/resources/hudson/tasks/junit/ClassResult/body.jelly
src/main/resources/hudson/tasks/junit/ClassResult/list.jelly
src/main/resources/hudson/tasks/junit/History/index.jelly
src/main/resources/hudson/tasks/test/AggregatedTestResultPublisher/TestResultAction/index.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/list.jelly
src/main/resources/lib/hudson/test/aggregated-failed-tests.jelly

This PR removes the usage of the 'pane-header' class. The class isn't needed, and it currently causes weird visuals in different themes:
* Tables look as expected

Remove 'pane-header' class usage

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/test/java/hudson/tasks/junit/CaseResultTest.java

`CaseResult.possiblyTrimStdio()` creates substrings according to UTF-16 (java `char`) boundaries. When stdio contains Unicode supplementary characters, this method can create unpaired surrogates by splitting a single unicode character "in half". Such strings can't be converted to UTF-8 and cause build failures:
```
FATAL: Failed to save the JUnit test result
java.io.IOException: java.lang.RuntimeException: Failed to serialize hudson.tasks.junit.TestResult#suites for class hudson.tasks.junit.TestResult
Caused by: java.lang.RuntimeException: Failed to serialize hudson.tasks.junit.TestResult#suites for class hudson.tasks.junit.TestResult
Caused by: java.lang.RuntimeException: Failed to serialize hudson.tasks.junit.SuiteResult#stderr for class hudson.tasks.junit.SuiteResult
Caused by: …
```

Prevent stdio trimming from creating invalid unicode data

---

src/main/resources/lib/hudson/test/js/failureSummary.js

Addresses https://github.com/jenkinsci/junit-plugin/issues/704
Removes any search parameter from the URL when showing test failures
Manual testing. Created job with failure report. Visited the test results page with a search query and then clicked on the failures.

Fix expand single failure

---

src/main/java/hudson/tasks/junit/JUnitResultArchiver.java

Observed in a CloudBees CI controller:
```
"org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution [#…] / waiting for JNLP4-connect connection from … id=…" Id=… Group=main TIMED_WAITING on hudson.remoting.UserRequest@…
at java.base@21.0.8/java.lang.Object.wait0(Native Method)
-  waiting on hudson.remoting.UserRequest@…
at java.base@21.0.8/java.lang.Object.wait(Object.java:366)
at hudson.remoting.Request.call(Request.java:179)
at hudson.remoting.Channel.call(Channel.java:1107)
at hudson.FilePath.act(FilePath.java:1204)
at hudson.FilePath.act(FilePath.java:1193)
at hudson.FilePath.copyTo(FilePath.java:2673)
at hudson.FilePath.copyTo(FilePath.java:2626)
at PluginClassLoader for junit-attachments//hudson.plugins.junitattachments.GetTestDataMethodObject.captureAttachment(GetTe …
```

Do not call `contributeTestData` with `WorkflowRun` lock held

---

src/main/java/hudson/tasks/junit/JUnitResultArchiver.java

Fixes #739. Reverts jenkinsci/junit-plugin#738.
Not exactly clear on what is going wrong but I think https://github.com/jenkinsci/junit-plugin/blob/71188fea0df5061d9d64a75d154469f6f59206ef/src/main/java/hudson/tasks/junit/TestResultAction.java#L125 is getting called too late.

Revert "Do not call `contributeTestData` with `WorkflowRun` lock held"

---

src/main/java/hudson/tasks/test/AggregatedTestResultPublisher.java

In attempting to diagnose an ATH failure I noticed what looks like a potential race condition that could lead to results not being correctly updated.
There is also issue where if jobs are not specified and are to be inferre,d then these are obtained from the dependency graph at action creation time, but the graph may not be correct at this point in time as it is built asynchronously.
There is also an other timing issue.
For example in rare cases (but maybe not so rare in our ATH) if 2 builds finish at T1, a web request comes in a T2 and then another build fishes at T3 followed by a web request at T4.
When T1 arrives the timestamp is set to T1, and then in T2 the current value is checked against the timestamp and set to T1+1
When T3 arrives the timestamp is set to T3.
THe issue occurs if …

race condition and missing results in aggregation
