jenkinsci/junit-plugin

src/main/java/hudson/tasks/junit/TestAction.java
src/main/java/hudson/tasks/test/TestObject.java

to make them accessible via the REST api.

Export the TestActions on the TestObject

---

src/main/resources/hudson/tasks/junit/JUnitResultArchiver/config.jelly

Discovered by @rpionke in https://github.com/jenkinsci/junit-plugin/pull/28
@reviewbybees

Remove the glitch symbol in the JUnitResultArchiver configuration

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/main/java/hudson/tasks/junit/SuiteResult.java
src/main/java/hudson/tasks/junit/TimeToFloat.java
src/test/java/hudson/tasks/junit/SuiteResultTest.java
src/test/resources/hudson/tasks/junit/junit-report-testsuite-time-attrs.xml

* #35 introduced getting suite time from attribute.
* However this did not work correctly when time was > 999.

[FIXED JENKINS-34407] Parse time correctly in SuiteResult.

---

pom.xml
src/main/java/hudson/tasks/junit/JUnitResultArchiver.java
src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java

https://issues.jenkins-ci.org/browse/JENKINS-26535
Required for https://issues.jenkins-ci.org/browse/JENKINS-28784
cc @reviewbybees esp @jglick

[JENKINS-28784] Workaround through using raw types for testDataPublishers

---

pom.xml
src/main/java/hudson/tasks/junit/JUnitResultArchiver.java

Symbol annotation

---

pom.xml
src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStep.java
src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStepExecution.java

Optional dependencies are evil and variants are eviller. KISS
Solves ATH regressions in `WorkflowPluginTest.{linearFlow,parallelTests}`.
@reviewbybees

Simplified dependencies

---

src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStepExecution.java
src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java

[JENKINS-48250](https://issues.jenkins-ci.org/browse/JENKINS-48250)

[FIXED JENKINS-48250] Log errors from JUnit parsing to FlowNode log

---

src/test/java/hudson/tasks/junit/SuiteResultTest.java

The issue number for nested test suites is JENKINS-6545, not JENKINS-6454.

Fix a referenced issue number

---

src/test/java/hudson/tasks/junit/pipeline/JUnitResultsStepTest.java
src/test/java/hudson/tasks/test/AggregatedTestResultPublisherTest.java

Fixes  https://issues.jenkins-ci.org/browse/JENKINS-47612
Followup of https://github.com/jenkinsci/junit-plugin/pull/85
This should fix all unit tests issues on Windows

Fix unit tests with shell/ batch to pass on Windows

---

.github/release-drafter.yml

Add Release Drafter to the repository

---

Jenkinsfile
pom.xml

Update POM, use BOM

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/test/java/hudson/tasks/junit/TestResultTest.java
src/test/resources/hudson/tasks/junit/junit-report-empty-testcasename.xml

Fixes https://issues.jenkins-ci.org/browse/JENKINS-63113
The UI for a testcase with an empty name looks then like this:

JENKINS-63113 use (?) as test name when empty in original report file

---

src/main/resources/hudson/tasks/test/AggregatedTestResultPublisher/config.jelly
src/main/resources/lib/hudson/test/blockWrapper.jelly

I couldn't see any actual issues caused by this, but may as well be safe
https://issues.jenkins-ci.org/browse/JENKINS-62912

JENKINS-62912 Improved tables to divs compat

---

src/main/java/hudson/tasks/junit/CaseResult.java
src/test/java/hudson/tasks/junit/storage/TestResultStorageTest.java

Add persisting duration

---

.mvn/extensions.xml
pom.xml
src/main/java/hudson/tasks/test/AggregatedTestResultPublisher.java
src/test/java/hudson/tasks/junit/JUnitResultArchiverTest.java

For compatibility with https://github.com/jenkinsci/jenkins/pull/4848.

Handle Acegi or Spring Security flavors of AccessDeniedException

---

src/main/java/io/jenkins/plugins/junit/storage/JunitTestResultStorageConfiguration.java

Load pluggable storage config from XML

---

src/main/java/hudson/tasks/junit/PackageResult.java
src/main/java/hudson/tasks/junit/TestResult.java
src/main/java/io/jenkins/plugins/junit/storage/TestResultImpl.java
src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

Only the test report duration in the top right missing now I think
No plans to implement description
Sub pages of the test report still need work

Implement test report table for pluggable storage

---

.gitignore
src/test/java/io/jenkins/plugins/junit/storage/benchmarks/BenchmarkRunner.java
src/test/java/io/jenkins/plugins/junit/storage/benchmarks/TrendGraphBenchmark.java

Left off CI for now as I don't think we need it

Add initial benchmark

---

src/main/java/hudson/tasks/test/TestResultProjectAction.java

Fixes https://github.com/jenkinsci/junit-plugin/issues/150

Find last build with action if current is null

---

src/main/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisher.java
src/test/java/io/jenkins/plugins/junit/checks/JUnitChecksPublisherTest.java

Fixes https://github.com/jenkinsci/junit-plugin/issues/221

Set 'No test results found' title on checks if no test results found

---

src/main/java/hudson/tasks/junit/JUnitResultArchiver.java

Prevents null pointer when using pluggable storage and checks api

JENKINS-64395 Pluggable storage checks api support

---

Jenkinsfile

Disable flakey windows builds

---

src/main/resources/hudson/tasks/test/TestResultProjectAction/jobMain.jelly

This is required for an upcoming core change related to tables to divs

Wrap project action in block element

---

README.md

Add link to contribution guidelines to README

---

pom.xml
src/main/java/hudson/tasks/junit/History.java
src/main/java/hudson/tasks/junit/HistoryTestResultSummary.java
src/main/java/io/jenkins/plugins/junit/storage/TestResultImpl.java
src/main/resources/hudson/tasks/junit/History/index.jelly
src/main/webapp/history/history.js
src/test/java/io/jenkins/plugins/junit/storage/TestResultStorageJunitTest.java

Fixes https://github.com/jenkinsci/junit-plugin/issues/165
and also:
* https://issues.jenkins.io/browse/JENKINS-64585
* https://issues.jenkins.io/browse/JENKINS-64586
* https://issues.jenkins.io/browse/JENKINS-64587
Will obsolete https://github.com/jenkinsci/junit-plugin/pull/263 assuming no test issues

API for history table in pluggable storage, fix JENKINS-64585, JENKINS-64586, JENKINS-64587

---

pom.xml
src/main/resources/hudson/tasks/junit/CaseResult/list.jelly
src/main/resources/hudson/tasks/junit/ClassResult/body.jelly
src/main/resources/hudson/tasks/junit/ClassResult/list.jelly
src/main/resources/hudson/tasks/junit/History/index.jelly
src/main/resources/hudson/tasks/test/AggregatedTestResultPublisher/TestResultAction/index.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/list.jelly
src/main/resources/lib/hudson/test/aggregated-failed-tests.jelly
src/test/resources/hudson/tasks/test/TrivialTestResult/body.jelly

The change proposed adapts the new table style provided by core.

Utilize new table style

---

src/test/java/hudson/tasks/test/TestResultExtensionTest.java

Ref https://github.com/jenkinsci/bom/pull/923

Switch `HudsonTestCase` to `JenkinsRule` in test

---

src/main/java/hudson/tasks/junit/TestResult.java

Make TestResult#getSuites(String) really null-safe

---

pom.xml

bump jackson2-api to avoid cyclic dependency

pin jackson2-api temporarily

---

README.md

This information is not available in github readme and in https://plugins.jenkins.io/junit/ 
Would be nice to have it here.

Add information about skipMarkingBuildUnstable in README.MD

---

src/main/java/hudson/tasks/junit/JUnitResultArchiver.java

Do not fail build when checks publishing breaks

---

.github/renovate.json

see https://github.com/jenkinsci/junit-plugin/pull/625#discussion_r1706244419

Skip 3.x of parallel-collectors in renovate

---

src/main/resources/hudson/tasks/junit/ClassResult/body.jelly
src/main/resources/hudson/tasks/test/MetaTabulatedResult/body.jelly
src/test/resources/hudson/tasks/test/TrivialTestResult/body.jelly

https://github.com/jenkinsci/junit-plugin/pull/660#issuecomment-2465965560

Use `Util#rawEncode` to encode URLs

---

src/main/java/hudson/tasks/test/TestObject.java

rawEncoding getSafeName within getRelativePathFrom in TestObject.java

---

src/main/java/hudson/tasks/junit/pipeline/JUnitResultsStep.java

Fixes https://github.com/jenkinsci/junit-plugin/issues/676
Tested generation with set to none and other options:

Fix pipeline snippet generator for StdIO retention

---

src/main/resources/hudson/tasks/test/TestObject/sidepanel.jelly

Migrate to EE 9 in Jelly view
